const assert = require('node:assert/strict');
const fs = require('node:fs');
const vm = require('node:vm');
const root = 'src/folder.view3/usr/local/emhttp/plugins/folder.view3/';
const fields = {};
for (const name of ['preview', 'name', 'icon', 'context', 'context_trigger', 'context_graph', 'context_graph_time', 'preview_text_width', 'preview_border_color']) fields[name] = { value: '', selectedOptions: [{ text: 'Combined' }] };
for (const name of ['preview_hover', 'preview_webui', 'preview_logs', 'preview_console', 'preview_update', 'expand_tab', 'update_column', 'preview_grayscale', 'preview_vertical_bars', 'preview_border', 'expand_dashboard', 'override_default_actions', 'default_action']) fields[name] = { checked: false };
fields.preview.value = '1'; fields.context.value = '0';
const classes = new Map();
const preview = { classList: { toggle: (key, enabled) => classes.set(key, enabled) }, style: { setProperty() {} }, querySelectorAll: () => [] };
const context = {};
const row = { addEventListener() {} };
const note = {};
const target = { innerHTML: '', querySelector: selector => ({ '.sample-row': row, '.sample-items': preview, '.sample-context': context, '.sample-note': note })[selector], querySelectorAll: () => [] };
const form = { elements: { namedItem: name => fields[name] }, addEventListener() {} };
const sandbox = { document: { querySelector: () => form, getElementById: () => target }, URLSearchParams, location: { search: '?type=docker' }, $: { i18n: key => key } };
vm.createContext(sandbox);
vm.runInContext(fs.readFileSync(root + 'scripts/include/escapeHtml.js', 'utf8') + '\n' + fs.readFileSync(root + 'scripts/folderPreview.js', 'utf8') + '\nglobalThis.render = updateFolderPreview;', sandbox);
assert.ok(target.innerHTML.includes('sample-update'));
fields.name.value = '<img onerror="bad">';
fields.preview.value = '4'; fields.preview_hover.checked = true;
fields.preview_border.checked = true; fields.preview_border_color.value = '#123456';
fields.expand_tab.checked = true; fields.context.value = '2';
sandbox.render();
assert.ok(target.innerHTML.includes('&lt;img onerror=&quot;bad&quot;&gt;'));
assert.equal(classes.get('sample-list'), true);
assert.equal(classes.get('sample-hover'), true);
assert.equal(preview.style.border, '1px solid #123456');
assert.ok(context.textContent.includes('CPU 2.00%'));
fields.preview.value = '0'; fields.update_column.checked = true;
sandbox.render();
assert.ok(target.innerHTML.includes('class="sample-items" hidden'));
assert.ok(!target.innerHTML.includes('sample-update'));
const page = fs.readFileSync(root + 'Folder.page', 'utf8');
assert.equal((page.match(/<fieldset/g) || []).length, 2);
assert.ok(page.indexOf('folder-live-preview') < page.indexOf('folder-basic-settings'));
console.log('Live preview regression checks passed');
